### ISSUE TITLE
question: using rollup.config.js

### ISSUE THREAD

**Issue by elmasse** [caseyWebb/taskr-rollup#11]
Hey Casey, 

Thanks for this cool plugin. I was wondering if it is possible to make it work with `rollup.config.js` by allowing passing no configuration into the plugin. Not sure if that is possible using rollup programmatically, but I hope so.

Let me know what you think, I can fork and create a PR in case you are interested.

Thanks again.
Max

**Comment by caseyWebb** [comment]
Should be dead simple to implement; taking the example from the README, you can re-use you `rollup.config.js` like this...

```javascript
exports.bundle = function * (task) {
  yield task
    // bundle entry file
    .source('src/entry.js')
    .rollup(require('./rollup.config.js'))
    .target('dist')
}
```

So, as far as I can tell, you should be able to just add a `require` in a try-catch in the lib to use the `rollup.config.js` if no config is specified (don't really want to get into merging configs; that gets messy).

You'd also have to ensure that it doesn't blow up if `input`, `output.file`, `output.format` are included in the rollup.config.js, but it should probably still log out that these fields will not be used if they are present.

**Comment by elmasse** [comment]
Thanks for your quick reply! That makes sense. I'll give it a try.
